import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :crit, CritWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is configured at runtime via the FORCE_SSL environment variable.
# See config/runtime.exs for details.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
